#!/usr/bin/env bash

# colors
if [[ "$1" == "zsh" ]]; then
    formatted_print=true
    light_red="%{\033[1;31m%}"
    cyan="[\033[0;36m%}"
    light_blue="%{\033[1;34m%}"
    light_purple="%{\033[1;35m%}"
    light_cyan="%{\033[1;36m%}"
    light_red="%{\033[0;31m%}"
    light_green="%{\033[0;32m%}"
    default_color="%{\033[00m%}"

else
    formatted_print=false
    light_red="\[\033[1;31m\]"
    cyan="[\033[0;36m\]"
    light_blue="\[\033[1;34m\]"
    light_purple="\[\033[1;35m\]"
    light_cyan="\[\033[1;36m\]"
    light_red="\[\033[0;31m\]"
    light_green="\[\033[0;32m\]"
    default_color="\[\033[00m\]"

fi




if [[ -d ./.svn ]]; then
    notclean=''
    if [[ `svn st | grep '^[ACDIMR?!~]' | wc -l` -gt 0 ]]; then
        notclean='${light_red}*'
    fi

    if [ $formatted_print ]; then
        echo "[\${cyan}SVN$notclean${default_color}]"
    else
        echo -e "[\${cyan}SVN$notclean${default_color}]"
    fi

else

    prefix=''
    branchinfo=`git branch -vv 2> /dev/null|grep '^*'`
    branch=`echo "$branchinfo" | sed -e 's/* \([^ ]*\).*$/\1/'`
    if [[ `echo "$branch"|wc -c` -gt "1" ]]; then
        files=`git ls-files -t -m -o --exclude-standard -d 2> /dev/null`

        gitsvn=false
        if [[ `git config --get svn-remote.svn.url | wc -l` -gt 0 ]]; then
            gitsvn=true
            prefix="$prefix\${cyan}gitsvn-"
        fi


        changed=''
        removed=''
        new=''
        not_pulled=''
        not_pushed=''
        not_committed=''

        if [[ `echo $files | grep '^[CM]' | wc -l` -gt 0 ]]; then
            changed="${light_red}*"
        fi

        if [[ `echo $files | grep '^[RK]' | wc -l` -gt 0 ]]; then
            removed="${light_red}!"
        fi

        if [[ `echo $files | grep '^?' | wc -l` -gt 0 ]]; then
            new="${light_blue}?"
        fi

        if $gitsvn ; then
            if [[ `git branch -r --contains HEAD | wc -l` -eq 0 ]]; then
                not_pushed="${light_purple}^"
            fi

        else
            tracking=`echo "$branchinfo"|sed -e 's/^.*\(.*\).*$/\1/'`

            if [[ `echo "$tracking" | grep behind | wc -l` -gt 0 ]]; then
                not_pulled="${light_cyan}v"
            fi

            if [[ `echo "$tracking" | grep ahead | wc -l` -gt 0 ]]; then
                not_pushed="${light_purple}^"
            fi
        fi

        if [[ `git diff-index HEAD | grep -v 00000000000000000000000000000000000 | wc -l` -gt 0 ]]; then
            not_committed="${light_red}$"
        fi

        if [ $formatted_print ]; then
            echo -e "[$prefix${light_green}$branch$changed$removed$new$not_pushed$not_pulled$not_committed${default_color}]"
        else
            echo "[$prefix${light_green}$branch$changed$removed$new$not_pushed$not_pulled$not_committed${default_color}]"
        fi
    fi
fi
