;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cabbage-kill-region-or-rm-kill-region-executor
        python-indent-dedent-line-backspace
        skeleton-pair-insert-maybe
        ))

(setq mc/cmds-to-run-once
      '(
        cabbage-kill-ring-save-or-rm-kill-ring-save-executor
        ))
