#!/bin/zsh

alias ls='ls -Gh'
alias ll='ls -l'
alias la='ls -lA'
alias l='la'
alias grep='grep --color'
alias Preview='/Applications/Preview.app/Contents/MacOS/Preview'

# emacs
alias e='/usr/local/bin/emacsclient -n'

# VIM
alias gvimp='gvim -p'
alias mvimdiff='mvim -d'
alias v='mvim --remote-tab-silent'
alias d='mvimdiff'

alias fakemail='sudo /usr/bin/python2.6 ~/bin/fakemail.py --host=localhost --port=25 --path=/Users/jone/temp/mails --background --open'

# rails
alias rss='script/server'
alias rsg='script/generate'
alias rsc='script/console'
alias pg='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log -m fast'
alias redis='redis-server /usr/local/etc/redis.conf'

# git
alias ga.='ga .'
alias ga='git add'
alias gb='git branch -v'
alias gba='git branch -a -v'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gco='git checkout'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gf='git fetch'
alias gl='git pull'
alias glg='git log --stat --max-count=5'
alias glo='git log'
alias glog='git log --graph'
alias glr='git pull --rebase'
alias gm='git merge'
alias gmf='git merge --ff-only'
alias gp='git push'
alias gr='git remote'
alias grs='git reset --hard'
alias gs='git status'
alias gsm='git submodule init'
alias gso='git show'
alias gsv='git svn'
alias gst='git config --add remote.origin.fetch "+refs/notes/*:refs/notes/*"'
alias gt='git notes --ref=jenkins show'
alias go='git browse'
alias gj='git jenkins'


# subversion
alias setSvnExternals='svn propset svn:externals -F ./EXTERNALS.TXT .'
alias setSvnIgnore='svn propset svn:ignore -F ./IGNORE.TXT .'

# scm
alias ssd='scm stash dry'
alias ss='scm stash'
alias ssa='scm stash apply'
alias ssl='scm stash list'

rationalise-dot() {
if [[ $LBUFFER != g* && $LBUFFER = *.. ]]; then
    LBUFFER+=/..
else
    LBUFFER+=.
fi
}
zle -N rationalise-dot
bindkey . rationalise-dot

alias ..='cd ..'
alias ../..='cd ../..'
alias ../../..='cd ../../..'
alias ../../../..='cd ../../../..'
alias ../../../../..='cd ../../../../..'
alias ../../../../../..='cd ../../../../../..'
alias ../../../../../../..='cd ../../../../../../..'
alias ../../../../../../../..='cd ../../../../../../../..'
alias ../../../../../../../../..='cd ../../../../../../../../..'
alias ../../../../../../../../../..='cd ../../../../../../../../../..'
alias ../../../../../../../../../../..='cd ../../../../../../../../../../..'
alias ../../../../../../../../../../../..='cd ../../../../../../../../../../../..'
alias ../../../../../../../../../../../../..='cd ../../../../../../../../../../../../..'


# Mac Application aliases
alias firefox='open -a firefox'
alias preview='open -a Preview'
alias camino='open -a Camino'
alias mail='open -a Mail'
alias skype='open -a Skype'
alias adium='open -a Adium'
alias ical='open -a ICal'
alias finder='open -a Finder'
alias notes='open -a Stickies'
alias tasks='open -a TaskCoach'
alias emacs='open -a Emacs'
alias taskcoach='open -a TaskCoach'
alias seleniumrc='/Users/jone/Apps/selenium-server-1.0.1/start_selenium_rc.sh'

# python stuff
alias manager='bin/manager/manager.py'
alias eggdist='python2.4 setup.py mregister sdist bdist_egg mupload -r '
alias refresh-buildout='git pull && (cd src && scmStat pull) && bin/buildout'

#Extensions
alias -s pdf=preview
alias -s odt=preview
alias -s doc=preview
alias -s docx=preview
alias -s rtf=preview
alias -s ods=preview
alias -s xls=preview
alias -s xlsx=preview
alias -s odp=preview
alias -s ppt=preview
alias -s pptx=preview

alias -s htm=firefox
alias -s html=firefox
alias -s xml=firefox

alias -s png=preview
alias -s jpg=preview
alias -s gif=preview

alias -s php=php
alias -s py=python

alias -s el=emacs
alias -s tsk=taskcoach

# phone remote control
alias phone_accept='curl "http://192.168.1.76/adr.htm?number=33"'
